# Generated by Django 5.0.3 on 2024-04-06 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('CNI', models.CharField(max_length=20)),
                ('date_d_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Non active', 'Non active'), ('Banned', 'Banned')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_exemplaire', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ISBN', models.CharField(max_length=13)),
                ('langue', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='muser',
            name='age',
        ),
        migrations.AddField(
            model_name='muser',
            name='Identifient',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_emprunt', models.DateField(auto_now_add=True)),
                ('Date_retourn', models.DateField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.client')),
                ('mUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.exemplaire')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.livre'),
        ),
    ]
