# Generated by Django 5.0.3 on 2024-04-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0003_livre_number_exemplaires_alter_client_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pret',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
