# Generated by Django 5.0.4 on 2024-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0004_livre_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='data_validite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
