# Generated by Django 5.0.4 on 2024-04-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0005_client_data_validite_alter_client_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='data_validite',
            new_name='date_validite',
        ),
    ]
