# Generated by Django 5.0.3 on 2024-04-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0006_rename_data_validite_client_date_validite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='disponible',
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='statut',
            field=models.CharField(default='Valable', max_length=50),
        ),
        migrations.AlterField(
            model_name='livre',
            name='langue',
            field=models.CharField(choices=[('', 'Select langue'), ('AR', 'Arabe'), ('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('AUTRE', 'Autre')], max_length=6),
        ),
    ]
