# Generated by Django 5.0.3 on 2024-04-17 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0008_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='pret',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.client')),
                ('exemplaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.exemplaire')),
                ('livre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lib_sys.livre')),
                ('respo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
