# Generated by Django 5.0.4 on 2024-04-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0009_alter_livre_pret_historique_delete_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='Date_retourne',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='statut',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='historique',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lib_sys.client'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='exemplaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lib_sys.exemplaire'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='livre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Lib_sys.livre'),
        ),
    ]
