# Generated by Django 5.0.4 on 2024-04-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0010_emprunt_date_retourne_alter_exemplaire_statut_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historique',
        ),
    ]
