# Generated by Django 5.0.4 on 2024-05-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0011_delete_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
