# Generated by Django 5.0.4 on 2024-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0012_alter_livre_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=1, upload_to='clients/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livre',
            name='cover',
            field=models.ImageField(default=1, upload_to='livre/'),
            preserve_default=False,
        ),
    ]
