# Generated by Django 5.0.4 on 2024-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lib_sys', '0013_client_image_livre_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='pret',
        ),
        migrations.AddField(
            model_name='livre',
            name='statut',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Hors_pret', 'Hors prêt')], default='Disponible', max_length=50),
        ),
    ]
